name: whatplane
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - pip
  # External Package Requirements
  - pytorch=1.7.1
  - torchvision=0.8.2
  - cudatoolkit=11
  - beautifulsoup4=4.9.3
  - pandas=1.1.4
  - requests=2.25.0
  - tensorboard=2.4.0
  - matplotlib
  - scikit-learn
  - tqdm
  - fastapi
  - uvicorn
  - azure-storage-blob
  # Devops Requirements
  - jupyter
  - pylint
  - click
  - black
  - radon
  - pytest
  - mypy
  # Install local package with pip
  # - pip:
  #   - -r file:requirements.txt