name: whatplane
dependencies:
  - python=3.8
  - pip
  # External Package Requirements
  - pytorch=1.7.0
  - torchvision=0.8.1
  - cuda=11
  - beautifulsoup4=4.9.3
  - pandas=1.1.4
  - requests=2.25.0
  - tensorboard=2.4.0
  # Devops Requirements
  - ipython
  - click
  - Sphinx
  - black
  - radon
  - pytest
  - mypy
  - coverage
  # Install local package with pip
  - pip:
    - -r file:requirements.txt